/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.flight_radar_simulator;

import java.util.Vector;

/**
 *
 * @author User
 */
public class Flight_Radar_Simulator extends javax.swing.JFrame {

    public static Vector<Airport> airports = new Vector<>();
    public static Vector<Plane> planes = new Vector<>();
    public static Scene myScene;
    private final SceneTimer sceneTimer;
    public static Table myTable;
    private final TableTimer tableTimer;

    public Flight_Radar_Simulator() {
        initComponents();

        Flight_Radar_Simulator.myScene = this.scene1;
        Flight_Radar_Simulator.myTable = this.table1;

        Flight_Radar_Simulator.airports.add(new Airport(200, 200, 1));
        Flight_Radar_Simulator.airports.add(new Airport(320, 60, 2));
        Flight_Radar_Simulator.airports.add(new Airport(80, 130, 3));
        Flight_Radar_Simulator.airports.add(new Airport(110, 310, 4));

        Airport airport0 = Flight_Radar_Simulator.airports.elementAt(0);
        Airport airport1 = Flight_Radar_Simulator.airports.elementAt(1);
        Airport airport2 = Flight_Radar_Simulator.airports.elementAt(2);

        Plane newPlane1 = new Plane(airport0.getX(), airport0.getY(), 5, 400, 1);
        newPlane1.setAirport(Flight_Radar_Simulator.airports.elementAt(0));

        Plane newPlane2 = new Plane(airport1.getX(), airport1.getY(), 5, 400, 2);
        newPlane2.setAirport(Flight_Radar_Simulator.airports.elementAt(0));

        Plane newPlane3 = new Plane(airport2.getX(), airport2.getY(), 5, 400, 3);
        newPlane3.setAirport(Flight_Radar_Simulator.airports.elementAt(0));

        Flight_Radar_Simulator.planes.add(newPlane1);
        Flight_Radar_Simulator.planes.add(newPlane2);
        Flight_Radar_Simulator.planes.add(newPlane3);

        this.sceneTimer = new SceneTimer();
        this.tableTimer = new TableTimer();
    }

    public static Airport getRandomAirport() {
        double random = Math.random() * Flight_Radar_Simulator.airports.size();
        return Flight_Radar_Simulator.airports.elementAt((int) random);
    }

    private static float getRandomX() {
        return (float) (Math.random() * Flight_Radar_Simulator.myScene.getWidth());
    }

    private static float getRandomY() {
        return (float) (Math.random() * Flight_Radar_Simulator.myScene.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        scene1 = new com.mycompany.flight_radar_simulator.Scene();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        table1 = new com.mycompany.flight_radar_simulator.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        scene1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, null));
        scene1.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout scene1Layout = new javax.swing.GroupLayout(scene1);
        scene1.setLayout(scene1Layout);
        scene1Layout.setHorizontalGroup(
            scene1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        scene1Layout.setVerticalGroup(
            scene1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        table1.setMaximumSize(new java.awt.Dimension(550, 400));
        table1.setMinimumSize(new java.awt.Dimension(550, 400));
        table1.setPreferredSize(new java.awt.Dimension(550, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scene1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(table1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scene1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (Plane p : Flight_Radar_Simulator.planes) {
            p.start();
        }
        sceneTimer.start();
        tableTimer.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        float randomX = Flight_Radar_Simulator.getRandomX();
        float randomY = Flight_Radar_Simulator.getRandomY();
        Plane newPlane = new Plane(randomX, randomY, 5, 400, Flight_Radar_Simulator.planes.size() + 1);
        newPlane.setAirport(Flight_Radar_Simulator.getRandomAirport());
        newPlane.start();
        Flight_Radar_Simulator.planes.add(newPlane);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int randomX = (int) Flight_Radar_Simulator.getRandomX();
        int randomY = (int) Flight_Radar_Simulator.getRandomY();
        Flight_Radar_Simulator.airports.add(new Airport(randomX, randomY, Flight_Radar_Simulator.airports.size() + 1));

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flight_Radar_Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flight_Radar_Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flight_Radar_Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flight_Radar_Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Flight_Radar_Simulator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.mycompany.flight_radar_simulator.Scene scene1;
    private com.mycompany.flight_radar_simulator.Table table1;
    // End of variables declaration//GEN-END:variables
}
